version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@14
  docker: circleci/docker@2.7.0

references:
  install_vault: &install_vault
    run:
      name: install hashicorp vault
      command: |
        apk --update add curl yq
        cd /tmp
        curl -LO https://releases.hashicorp.com/vault/1.13.2/vault_1.13.2_linux_amd64.zip
        sha256sum vault_1.13.2_linux_amd64.zip | grep f7930279de8381de7c532164b4a4408895d9606c0d24e2e9d2f9acb5dfe99b3c
        unzip vault_1.13.2_linux_amd64.zip
        mv vault /usr/bin/vault

workflows:
  version: 2
  build:
    jobs:
      - docker/publish:
          after_checkout:
            - *install_vault
            - rok8s/get_vault_env:
                vault_path: repo/global/env
          image: quay.io/fairwinds/yelb-ui
          cache_from: quay.io/fairwinds/yelb-ui:v0.1.0
          docker-password: FAIRWINDS_QUAY_TOKEN
          docker-username: FAIRWINDS_QUAY_USER
          filters:
            branches:
              only: /.*/
            tags:
              only: /v.*/

